### PR TITLE
Bug fix in components/plot_radar.py

### PR DESCRIPTION
**Pull request by tjlang**
In components/plot_radar.py, there is an error introduced when working
with NEXRAD files that have been converted away from Level 2 by
RadxConvert and have had their split-cut sweeps merged. When looping
over self.rTilts in RadarDisplay, if you do not loop over the array
indices themselves, you will get an IndexError and artview will crash
because sweep numbers and index numbers do not match. I fixed this with
enumerate().

During the error tracking process, I also applied pep8 to following:
__main__.py (did not address pep8 complaint about location of artview
import)
scripts/standard.py
components/plot_radar.py

### CODE REVIEW

**Comment by gamaanderson** [comment]
thank you for catching this @nguy. We really should not use a variable (sweep number) for index.

**Comment by nguy** [comment]
Nice catch Tim. 
I noticed that the Custom Tool is still in the Display Tools list. I'm thinking that we could have a plugin called CreateCustomPlugin that brings up a text window with  information on creating a plugin and the website with the directions. Any objections?

**Comment by gamaanderson** [comment]
The idea of this  CreateCustomPlugin its kind of strange to me, its not like one could create a plugin in just as few lines. Place that in the Display is also kind of not the right place. Any way I wouldn’t say I have objections, I'm not voting it down in any way, I just find it really strange.

**Comment by nguy** [comment]
If we don't think it's the right place that's fine. Maybe it's better to keep this to the documentation and not try to confuse things.

**Pull request merged**
