### PR TITLE
Please Merge: python3 bug

### PR DESCRIPTION
**Pull request by gamaanderson**
Current master is not working with Python3 (bug on __main__)

Also FIY Python3 Basemap is still not available in Debian Stable (it will be in the next release)

### CODE REVIEW

**Comment by gamaanderson** [comment]
Do not merge, this got contaminated with an other commit. If you want apply just the first commit.

**Comment by nguy** [comment]
I know this is closed, but should we merge the original commit soon?

**Comment by gamaanderson** [comment]
if you want it is just 3 lines. But as soon as you are done with the text I will open a PR for PyQt5, so it will not take long.

**Comment by nguy** [comment]
Let's do this as a separate PR though.

**Pull request closed without merging**
