### PR TITLE
BUG: getPathInteriorValues for RHI and Airborne

### PR DESCRIPTION
**Pull request by gamaanderson**

### CODE REVIEW

**Comment by nguy** [comment]
Conversation from PR #100 should continue here

**Comment by nguy** [comment]
Addressing a comment I made about limits - disregard. We can easily connect the limits between displays when looking at the differences.

**Comment by nguy** [comment]
See the image provided. The selected region should return NaN if originally NaN values, not zero as it is now.
screen shot 2015-12-14 at 4 26 52 pm

**Comment by nguy** [comment]
FileList is fixed, nice work!

**Comment by gamaanderson** [comment]
@nguy thank you for the bugreport, i hope it is solved now.

**Comment by nguy** [comment]
Nice, that looks good.

**Comment by nguy** [comment]
Seems to be working from my limited tests. Any other changes you want to make?

**Comment by gamaanderson** [comment]
As long as there are no other bugs, that is all.

**Comment by nguy** [comment]
No further chatter so I'm going to merge. We can always create further PRs if needed later down the line.

**Pull request merged**
