### PR TITLE
Added 'reflectivity_horizontal' as possible field to check to work with ...

### PR DESCRIPTION
**Pull request by swnesbitt**
...ARM-CSAPR data

### CODE REVIEW

**Comment by nguy** [comment]
@swnesbitt Thanks!  It's added and I'll push the change soon.  Some SSL handshake error with Github this morning.  A little research suggests this happens time-to-time.

**Comment by nguy** [comment]
Success!

**Comment by swnesbitt** [comment]
Stick a fork in it?

Sent from my iPhone

On Mar 27, 2015, at 12:12 PM, Nick <notifications@github.com<mailto:notifications@github.com>> wrote:


Success!

**Comment by nguy** [comment]
Absolutely!

**Pull request merged**
