### PR TITLE
Issue #14

### PR DESCRIPTION
**Pull request by gamaanderson**
This is a major PR, push all changes you have so that I can merge them before the PR.
Tree major alterations:

1. Create Abstract component class from which all other derivate
2. Create ComponentsControl, I believe the use is intuitive, but suggestion are always welcome
3. Add layout and components menu in MainMenu, take a look in how it works, you may need to increase MainMenu window to see it. Also play with lines 36 and 37 in `execute_two.py`, comment each one of them out and see what happen.

### CODE REVIEW

**Comment by nguy** [comment]
@gamaanderson The master should be up-to-date.

**Comment by gamaanderson** [comment]
then it can be merge

**Comment by gamaanderson** [comment]
Just add commit showing how to add plugins (user defined components). Its just preliminary, it need some adjustments.

**Comment by nguy** [comment]
I'll get to this soon.  Busy end of the week for me.  Looking forward to browsing through the changes. Thanks!

**Comment by gamaanderson** [comment]
ok, take your time.

**Comment by nguy** [comment]
Okay, I had a chance to float through this a bit this morning. This is an incredibly powerful tool.  I'll comment below on various things before merging.
Let me make sure I understand a couple of things.  
The 'Layout' menu grows with each component that you add? I see that removing the default (Components) disables that menu.  Is there a way to regenerate the menu?

1. I don't see much difference when commenting in/out L36/37. As far as I could tell the operation was the same? Okay after a little  more playing around L36 omits the layout menu from building.  It also results in the Components(?) window being on top and not buried (item #3).

2. I think we will need to rework the wording to explain what is happening here.  It took me a minute to figure out and I think someone with no experience of diving into our code and conversations will be lost.

3. Currently this window gets buried by the Display plots.  We should find a way to put it to the front or different location to make sure people know it is there.  Maybe this should even be callable via the Mainmenu (maybe that is what you did there)?

4. I like how this will allow the user to add their own component. I think we will need to be vigilant in documentation for this to be used properly (even with advanced users) just because it is a unique interface.

5.

**Comment by gamaanderson** [comment]
yes, the layout menu grow with every new add! once empty it also reopen with a new add, for instance using the components menu

1. L36 put ComponentsControl inside MainMenu, instead of being a separated window. L37 add the possibility of re-opening ComponentsControl using the components menu in the menubar of MainMenu

2. I'm always open for suggestions in wording. I'm naturally not good in that, in Portuguese (my native language) , English or German.

3. I think there are some gui ways of adjusting this things, but its complicate to get it right as it depends on screen size. We will have to test a litte, I would just point out this configuration are to be done in the **execute** file

4. You'r right: documentation, documentation, documentation!

**Pull request merged**
