### PR TITLE
Radar terminal

### PR DESCRIPTION
**Pull request by gamaanderson**
PR #164 

give a look how this works, just as the video in the discussion. As before I still rely into the system terminal.

### CODE REVIEW

**Comment by nguy** [comment]
I like the idea and I view this as an ongoing development topic. This PR should provide a template to begin. That said, I still find it a bit hard to use, probably because I haven't used it extensively. I would still like to see an easy GUI interface attached for simpler operations such as multiply or add a factor to a field.

**Comment by nguy** [comment]
I'm happy merging this in as-is, it seems stable and extensible. And then we can continue to bulk this out as we go ahead. 

One thing that could be useful is brief example in the Help text mocking a terminal operation.

**Comment by gamaanderson** [comment]
adding a constant (e.g. 10) is as easy as:

    reflectivity += 10

or

    new_reflectivity = reflectivity + 10
    add_field("new_reflectivity")

**Comment by nguy** [comment]
Yes, I was able to easily do this following your tutorial. I was just saying that maybe we could add exactly what you posted into the Help as a brief and pertinent example.

**Comment by gamaanderson** [comment]
just updated the help

**Comment by nguy** [comment]
Alright, let's merge this to continue momentum.

**Pull request merged**
