### PR TITLE
STY: Override MacOSX menu placement to show in MainMenu window.

### PR DESCRIPTION
**Pull request by nguy**
This implements a check to see if the OS is Mac and applies an override of menu placement if it is. Mentioned in Issue #130.

### CODE REVIEW

**Comment by nguy** [comment]
I'd like to be more consistent about micro revs when making these changes. If we decide to merge this.

**Comment by gamaanderson** [comment]
when do we change the micro? we can't do it at every small PR.

**Comment by nguy** [comment]
Nope, for example the airborne PR I don't think needs this change. However, since this changes the operation on the Mac side (moving menu from top to menu window), I think the operation of the package has changed and therefore the micro should be rolled. My thought is that fixes and small changes should not roll the micro version, but when the way ARTview operates changes (both to user and on developer side), then we roll numbers. Thoughts?

**Comment by nguy** [comment]
@gamaanderson What do you think about this PR?

**Comment by gamaanderson** [comment]
could you make that test in `view.start`?

**Comment by nguy** [comment]
Added that and also to ```artview.scripts.view```. These were the 3 places I found an instance of ```app```.

**Comment by gamaanderson** [comment]
ok, i'm fine with merging

**Comment by nguy** [comment]
Great. What do you think about a rev roll for this?

**Comment by nguy** [comment]
I'm also going to close Issue #130 for the time being. I don't think the original argument can be addressed at the moment.

**Comment by gamaanderson** [comment]
I have no problem with rolling the version, but doing it before merging will create a conflict.

**Comment by nguy** [comment]
Ah because of the other PR we just did.

**Pull request merged**
