### PR TITLE
Improvementes

### PR DESCRIPTION
**Pull request by gamaanderson**
Here are a series of improvements I have being working, they are intent to improve the user experience. Those Include:
    
* remove the example plugins
* improve window placement in standard script
* add -F option to open file directly, no dialog
* change standard field from 'reflectivity' to pyart.config.get_field_name('reflectivity')
* add test to avoid breaking down dow to incorrect field
* calculate_attenuation and phase_proc_lp plugins name to capital letters
* add frames to the Menu layout elements
* add option to have plugins in Menu or as Independent windows

### CODE REVIEW

**Comment by gamaanderson** [comment]
@nguy if you would allow me, I would like to merge all pull-request and a correction to issues #38 into a single PR to be merged all at once into master

**Comment by nguy** [comment]
You bet. How do you want to approach this?

I'll hold off trying to merge anything for the time being. Let me know when you deem it ready.

**Comment by gamaanderson** [comment]
I will merge everything into a branch a create a pull request, merging this will automatically close the other ones, also as long as you don't do any more commits there will be no conflicts. Even if you do make a commit, I don't expect too much trouble.

**Comment by nguy** [comment]
My commits should be done for a bit. Have to focus on some other work for a while.
I look forward to your merged commit. Looks like some great stuff in there!

**Pull request merged**
