### PR TITLE
ROI and infolabel update.

### PR DESCRIPTION
**Pull request by nguy**
Added column headers to ROI saved CSV files.
Update open ROI saved files.
Enhanced error checking in ROI.
Added ROI stats output.
Fix LongMessage modeless to display.
Fixed a minor bug for Python 2.6
Added a tool reset button.
Updated infolabel.

### CODE REVIEW

**Comment by nguy** [comment]
This takes care of a few comments from both @tjlang and @pfhein Issues #53 and #47 .
I also updated some ROI functionality, which led to a hopefully more robust modeless dialog window.

I also added a tooltip to self.canvas in ```plot_radar.py```, but I need suggestions on how to get the filename over the Display class. I balked at putting it in the new infolabel box at top after remembering how long file names can be. A subtle solution is a hover-over on the plot that will give the name. Of course this could cause problems with using the tools. Thoughts?

Maybe we could attach the tooltip to another feature?

**Comment by gamaanderson** [comment]
About the filename, I am sure in my mind, the only `legal` way of passing it from Menu to Display is with a shared variable, however a Vfilename variable does not make sense, since I can not image of a use for component having Vradar unrelated to Vfilename. So if the official doors are closed, you smuggle it in. And radar is perfect for that.

**Comment by nguy** [comment]
I spent some time floating through the code and looking online and yes it seems you are right given our setup. And I agree that a Vfilename seems unnecessary. As Tim pointed out, since the title is able to be changed (by design) it may not be the best way to tell what file you are reading at the moment. Plus, I've had instances of really not knowing from the auto-generated title. A quick reference would be nice here.

I may try the smuggle route with Vradar, attaching the filename as you previously suggest in ```Menu```. This can always be changed later if we deem it not worthy.

**Comment by nguy** [comment]
Okay, updated the titles per conversation in #53 and also smuggled the filename into Display as discussed in #65 . The hover tool is now over the info label to see what file you are working on.

**Comment by nguy** [comment]
I also made the change to LinkDisplay per #53 . Using the grep command it wasn't too bad, just need to be diligent in doing that.
Other changes I'm considering is ```RadarDisplay``` to ```AddDisplay``` and ```ROI``` to ```SelectRegion```. This might mean renaming ```roi.py``` to ```select_region.py``` also, but this is actually more clear. Thoughts?

**Comment by pfhein** [comment]
Yes, SelectRegion is more descriptive than ROI.  I like the changes.

**Comment by gamaanderson** [comment]
I don't like AddDisplay, Radar is important to separate from display, and add don't make sense as class name. If you want you can put add before all entries:
`"add " + comp.__name__` in  [here](https://github.com/nguy/artview/blob/master/artview/components/menu.py#L245)

**Comment by nguy** [comment]
See #53 for my comment on AddDisplay, I agree and didn't change this.

Unfortunately I don't think "add" is appropriate as we're not really adding atteuation calculation they are being performed. And I like those names already.

I would go for ```LinkPlugins``` instead of ```LinkDisplay```.

**Comment by gamaanderson** [comment]
would "start" be better than "add"?

**Comment by nguy** [comment]
Okay, the check is added and will be pushed with next commit.
I also changed the name from ```LinkDisplay``` to ```LinkPlugins```. Does that work?

**Comment by gamaanderson** [comment]
yes, it does

**Comment by nguy** [comment]
Okay, the points.py has been added to core directory. I'm going to go ahead an merge.

**Comment by gamaanderson** [comment]
Ok, go on and merge. By the way are you planning any more alterations?

**Comment by nguy** [comment]
I will hold off for a bit. Are you going to implement something?

**Comment by gamaanderson** [comment]
May be just some minor stuff to further round the edges.

**Comment by nguy** [comment]
Sounds good. I have a couple of thoughts of things to do. One more addition
to SelectRegion and make the masking plugin.

**Comment by gamaanderson** [comment]
Do you want to do that before or after I convert SelectRegion to use Points?

**Comment by nguy** [comment]
Let me see if I can knock this out in the next day or two. If not I'll post here again.

Using the points won't change the functionality of SelectRegion, correct?

**Comment by gamaanderson** [comment]
correct, the functionality will not change, just how the data is stored.

**Comment by nguy** [comment]
I'm going to make just a couple quick changes and then I'll do another small PR.

I *may* have found a slightly more elegant test solution for the ```_check_default_field``` in ```plot_radar.py```. We'll see what others think. It came out of a conversation with @pfhein about how another software works.

**Pull request merged**
