### PR TITLE
add despeckle

### PR DESCRIPTION
**Pull request by gamaanderson**
issue #152

### CODE REVIEW

**Comment by nguy** [comment]
This is really nicely done @gamaanderson . Great addition!

I think that we need to put some help info somewhere. Especially for the ```object_field```.

**Comment by gamaanderson** [comment]
just add more info to object_field and despeckle button

**Comment by nguy** [comment]
That looks great. I'd say we can merge if you are okay with that.

**Comment by gamaanderson** [comment]
Yes, I think that is all.

**Pull request merged**
