### PR TITLE
BUG: force matplotlib to use PyQt4 as backend

### PR DESCRIPTION
**Pull request by gamaanderson**
Solve bug reported in issue #80

### CODE REVIEW

**Comment by nguy** [comment]
@gamaanderson Did you get the following warning as well?
```/Users/guy/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:1318: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.```

**Comment by gamaanderson** [comment]
yes, actually I also get this warning. It got lost in my terminal, so I didn't saw it. I wounder however if this line as any effect at all. The important is probably the second one.

**Comment by nguy** [comment]
I recall seeing that issues could arise from having PySide instead of PyQt (there were some tests that could be used to call either) when I originally switched the code from Tkinter in January. There are slight differences in a few calls if using PySide vs. PyQt as well. Just for future reference I'll put a [link to differences](http://wiki.qt.io/Differences_Between_PySide_and_PyQt) in this thread.

**Comment by nguy** [comment]
I doubt it causes any issues, but we'll see if it fixes the problem.

**Comment by vanandel** [comment]
After I pulled the latest changes to pyart: 
commit 20afb010eeeccaeeabd4457241b2eeb6a4870b7e
Merge: de80c70 05f38f9
Author: Nick Guy <nguysur@gmail.com>
Date:   Wed Aug 19 08:45:23 2015 -0600

I still get the same error message, shown below.

Also, is it possible to suppress the message "Unable to simultaneously satisfy constraints"?

/usr/local/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:1318: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
2015-08-19 10:04:44.365 python[79925:2804616] Unable to simultaneously satisfy constraints:
(
    <NSAutoresizingMaskLayoutConstraint:0x111063ad0 h=--& v=--& V:[NSView:0x115075970(0)]>,
    <NSAutoresizingMaskLayoutConstraint:0x1110d4e40 h=-&- v=-&- V:|-(0)-[FI_TListScrollView:0x115079e80]   (Names: '|':NSView:0x115075970 )>,
    <NSAutoresizingMaskLayoutConstraint:0x1110d6690 h=-&- v=-&- V:[FI_TListScrollView:0x115079e80]-(0)-|   (Names: '|':NSView:0x115075970 )>,
    <NSAutoresizingMaskLayoutConstraint:0x1129e6310 h=-&- v=-&- V:[NSClipView:0x115079a40]-(15)-|   (Names: '|':FI_TListScrollView:0x115079e80 )>,
    <NSAutoresizingMaskLayoutConstraint:0x1129e6130 h=-&- v=-&- V:|-(0)-[NSClipView:0x115079a40]   (Names: '|':FI_TListScrollView:0x115079e80 )>
)

Will attempt to recover by breaking constraint
<NSAutoresizingMaskLayoutConstraint:0x1129e6310 h=-&- v=-&- V:[NSClipView:0x115079a40]-(15)-|   (Names: '|':FI_TListScrollView:0x115079e80 )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
Opening file /scr/eldora2/rsfdata/front/cfradial/spol/qpe/20140520/cfrad.20140520_170440.000_to_20140520_170440.000_SPOL_v0_s00_el0.00_SUR.nc
Traceback (most recent call last):
  File "/usr/local/anaconda/bin/artview", line 5, in <module>
    artview.__main__.main(sys.argv)
  File "/usr/local/anaconda/lib/python2.7/site-packages/artview/__main__.py", line 18, in main
    artview.run(DirIn, filename, field)
  File "/usr/local/anaconda/lib/python2.7/site-packages/artview/scripts/standard.py", line 50, in run
    parent=MainMenu)
  File "/usr/local/anaconda/lib/python2.7/site-packages/artview/components/plot_radar.py", line 142, in __init__
    self.LaunchGUI()
  File "/usr/local/anaconda/lib/python2.7/site-packages/artview/components/plot_radar.py", line 171, in LaunchGUI
    self._set_figure_canvas()
  File "/usr/local/anaconda/lib/python2.7/site-packages/artview/components/plot_radar.py", line 677, in _set_figure_canvas
    self.layout.addWidget(self.canvas, 1, 0, 7, 6)
TypeError: arguments did not match any overloaded call:
  QGridLayout.addWidget(QWidget): argument 1 has unexpected type 'FigureCanvasQTAgg'
  QGridLayout.addWidget(QWidget, int, int, Qt.Alignment alignment=0): argument 1 has unexpected type 'FigureCanvasQTAgg'
  QGridLayout.addWidget(QWidget, int, int, int, int, Qt.Alignment alignment=0): argument 1 has unexpected type 'FigureCanvasQTAgg'

**Comment by nguy** [comment]
Okay, I added a little snippet in the ```__init__.py```. This takes care of the warning message on my machine. Can you grab the changes and try?

**Comment by vanandel** [comment]
I pulled your change - no difference

/usr/local/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:1318:
UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
2015-08-19 13:54:46.872 python[82951:2958946] Unable to simultaneously
satisfy constraints:
(
    <NSAutoresizingMaskLayoutConstraint:0x1150830f0 h=--& v=--&
V:[NSView:0x1129b57f0(0)]>,
    <NSAutoresizingMaskLayoutConstraint:0x11509e450 h=-&- v=-&-
V:|-(0)-[FI_TListScrollView:0x1129a9c20]   (Names: '|':NSView:0x1129b57f0
)>,
    <NSAutoresizingMaskLayoutConstraint:0x11509e400 h=-&- v=-&-
V:[FI_TListScrollView:0x1129a9c20]-(0)-|   (Names: '|':NSView:0x1129b57f0
)>,
    <NSAutoresizingMaskLayoutConstraint:0x11509b7b0 h=-&- v=-&-
V:[NSClipView:0x1129a9910]-(15)-|   (Names:
'|':FI_TListScrollView:0x1129a9c20 )>,
    <NSAutoresizingMaskLayoutConstraint:0x11509b760 h=-&- v=-&-
V:|-(0)-[NSClipView:0x1129a9910]   (Names:
'|':FI_TListScrollView:0x1129a9c20 )>
)

Will attempt to recover by breaking constraint
<NSAutoresizingMaskLayoutConstraint:0x11509b7b0 h=-&- v=-&-
V:[NSClipView:0x1129a9910]-(15)-|   (Names:
'|':FI_TListScrollView:0x1129a9c20 )>

Set the NSUserDefault
NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have
-[NSWindow visualizeConstraints:] automatically called when this happens.
And/or, break on objc_exception_throw to catch this in the debugger.
Opening file /scr/eldora2/rsfdata/front/cfradial/spol/qpe/20140520/
cfrad.20140520_170440.000_to_20140520_170440.000_SPOL_v0_s00_el0.00_SUR.nc
Traceback (most recent call last):
  File "/usr/local/anaconda/bin/artview", line 5, in <module>
    artview.__main__.main(sys.argv)
  File
"/usr/local/anaconda/lib/python2.7/site-packages/artview/__main__.py", line
18, in main
    artview.run(DirIn, filename, field)
  File
"/usr/local/anaconda/lib/python2.7/site-packages/artview/scripts/standard.py",
line 50, in run
    parent=MainMenu)
  File
"/usr/local/anaconda/lib/python2.7/site-packages/artview/components/plot_radar.py",
line 142, in __init__
    self.LaunchGUI()
  File
"/usr/local/anaconda/lib/python2.7/site-packages/artview/components/plot_radar.py",
line 171, in LaunchGUI
    self._set_figure_canvas()
  File
"/usr/local/anaconda/lib/python2.7/site-packages/artview/components/plot_radar.py",
line 677, in _set_figure_canvas
    self.layout.addWidget(self.canvas, 1, 0, 7, 6)
TypeError: arguments did not match any overloaded call:
  QGridLayout.addWidget(QWidget): argument 1 has unexpected type
'FigureCanvasQTAgg'
  QGridLayout.addWidget(QWidget, int, int, Qt.Alignment alignment=0):
argument 1 has unexpected type 'FigureCanvasQTAgg'
  QGridLayout.addWidget(QWidget, int, int, int, int, Qt.Alignment
alignment=0): argument 1 has unexpected type ‘FigureCanvasQTAgg'

**Comment by nguy** [comment]
Hmmmm, weird. Can you start python in a shell and run the following and tell me what comes out?
```
import matplotlib
matplotlib.get_backend()
```

**Comment by gamaanderson** [comment]
I would also be interested in the test script I posted in the original issue (#80), because I've run out of ideas.

@nguy, do you know that are those constraints?

**Comment by nguy** [comment]
I'm not sure what is going on. Done some looking and can't seem to find any information matching the symptoms thus far.

With the above code, I wanted to make sure that MacOS was listed as is on my machine.

I also realized I mistyped this line ```matplotlib.use('Agg')``` in ```__init__.py``` . It should read ```matplotlib.use('Qt4Agg')```.

I pushed a change. This could affect the behavior because 'Agg' is for machines with no interactive GUI.

**Comment by vanandel** [comment]
Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import matplotlib
>>> matplotlib.get_backend()
u'MacOSX'
>>>

**Comment by vanandel** [comment]
No change after pulling:
l$ artview
2015-08-19 17:08:54.919 python[85448:3058449] Unable to simultaneously
satisfy constraints:
(
    <NSAutoresizingMaskLayoutConstraint:0x115081230 h=--& v=--&
V:[NSView:0x11503ed10(0)]>,
    <NSAutoresizingMaskLayoutConstraint:0x115080c80 h=-&- v=-&-
V:|-(0)-[FI_TListScrollView:0x115042e60]   (Names: '|':NSView:0x11503ed10
)>,
    <NSAutoresizingMaskLayoutConstraint:0x115080c30 h=-&- v=-&-
V:[FI_TListScrollView:0x115042e60]-(0)-|   (Names: '|':NSView:0x11503ed10
)>,
    <NSAutoresizingMaskLayoutConstraint:0x115036220 h=-&- v=-&-
V:[NSClipView:0x115042ab0]-(15)-|   (Names:
'|':FI_TListScrollView:0x115042e60 )>,
    <NSAutoresizingMaskLayoutConstraint:0x1150361d0 h=-&- v=-&-
V:|-(0)-[NSClipView:0x115042ab0]   (Names:
'|':FI_TListScrollView:0x115042e60 )>
)

Will attempt to recover by breaking constraint
<NSAutoresizingMaskLayoutConstraint:0x115036220 h=-&- v=-&-
V:[NSClipView:0x115042ab0]-(15)-|   (Names:
'|':FI_TListScrollView:0x115042e60 )>

Set the NSUserDefault
NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have
-[NSWindow visualizeConstraints:] automatically called when this happens.
And/or, break on objc_exception_throw to catch this in the debugger.
Opening file /scr/eldora2/rsfdata/front/cfradial/spol/qpe/20140520/
cfrad.20140520_170440.000_to_20140520_170440.000_SPOL_v0_s00_el0.00_SUR.nc
Traceback (most recent call last):
  File "/usr/local/anaconda/bin/artview", line 5, in <module>
    artview.__main__.main(sys.argv)
  File
"/usr/local/anaconda/lib/python2.7/site-packages/artview/__main__.py", line
18, in main
    artview.run(DirIn, filename, field)
  File
"/usr/local/anaconda/lib/python2.7/site-packages/artview/scripts/standard.py",
line 50, in run
    parent=MainMenu)
  File
"/usr/local/anaconda/lib/python2.7/site-packages/artview/components/plot_radar.py",
line 142, in __init__
    self.LaunchGUI()
  File
"/usr/local/anaconda/lib/python2.7/site-packages/artview/components/plot_radar.py",
line 171, in LaunchGUI
    self._set_figure_canvas()
  File
"/usr/local/anaconda/lib/python2.7/site-packages/artview/components/plot_radar.py",
line 677, in _set_figure_canvas
    self.layout.addWidget(self.canvas, 1, 0, 7, 6)
TypeError: arguments did not match any overloaded call:
  QGridLayout.addWidget(QWidget): argument 1 has unexpected type
'FigureCanvasQTAgg'
  QGridLayout.addWidget(QWidget, int, int, Qt.Alignment alignment=0):
argument 1 has unexpected type 'FigureCanvasQTAgg'
  QGridLayout.addWidget(QWidget, int, int, int, int, Qt.Alignment
alignment=0): argument 1 has unexpected type 'FigureCanvasQTAgg'

**Comment by vanandel** [comment]
python /tmp/testmp.py

Traceback (most recent call last):
  File "/tmp/testmp", line 24, in <module>
    win.setCentralWidget(canvas)
TypeError: QMainWindow.setCentralWidget(QWidget): argument 1 has unexpected
type ‘FigureCanvasQTAgg'

I uncommented
matplotlib.use('Qt4Agg’)  - no difference

I uncommented
matplotlib.rcParams['backend.qt4']=‘PyQt4’ - no difference

Here are the versions you wanted:

matplotlib.__version__
‘1.4.3'
from PyQt4.QtCore import QT_VERSION_STR
>>> QT_VERSION_STR
‘4.8.6'

from PyQt4.pyqtconfig import Configuration
>>> cfg = Configuration()
>>> cfg.pyqt_version_str
‘4.11.3

Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42)

**Comment by gamaanderson** [comment]
I've made a question in [Stackoverflow](http://stackoverflow.com/questions/32108245/matplotlib-pyqt-not-working-in-ox), lets see how that goes.

**Comment by nguy** [comment]
According to the comment the issue you posted, do you think that by leaving the other 
```
import matplotlib
matplotlib.use('Qt4Agg')
matplotlib.rcParams['backend.qt4']='PyQt4'
```
in other modified scripts when I added to the __init__.py it caused this issue?

**Comment by vanandel** [comment]
Sorry, I don’t know.

**Comment by nguy** [comment]
Sorry @vanandel that last comment was directed at @gamaanderson

**Comment by nguy** [comment]
@vanandel On the Stackoverflow that was submitted, one comment suggested that importing components multiple times might contribute. I commented out the other additions from this original pull request and only left the first instance I added in the __init__.py.
Would you pull changes and see if the error changes (or goes away, fingers crossed)?

Also do you still get the matplotlib.use() warning at startup?

**Comment by gamaanderson** [comment]
sorry, I forgot to answer.

letting just one call of `matplotlib.use()` in `__init__.py` remove the `matplotlib.use() has no effect` warning, but this only cosmetic as it does not solve the problems. 

The  constraints, I don't know what they are to being with, have never seen and the internet did not help.

**Comment by nguy** [comment]
When I added the code to the ```__init__.py``` the warning you note went away on my machine. Is it still present on your computer @gamaanderson ?

Yeah this one seems tough, not finding much help online.

**Comment by gamaanderson** [comment]
you are right, the warning is already gone.

**Comment by nguy** [comment]
Okay I'll take a small victory. :) For some reason it needed to be put in front of all folder imports that load the functions you had added it to originally. It must have something to do with how those were opened and in fact imported matplotlib before those were enabled. By sticking the code before anything was loaded initially, it got around that.

**Comment by nguy** [comment]
From this [discussion](http://stackoverflow.com/questions/14327145/unable-to-simultaneously-satisfy-constraints-no-constraints-in-place) it may be that the window sizes are causing the issue.

**Comment by nguy** [comment]
So @gamaanderson you said you were able to recreate the problem? 
What did you do to recreate? Are you still unable to open?

I'm wondering after floating around the web a bit more if it has something to do with the menu width and height definitions on startup. The only things I can find have to do with mostly mobile applications with resizable windows.

**Comment by gamaanderson** [comment]
@vanandel in the test script you could replace

    from PyQt4 import QtCore, QtGui

by

    from matplotlib.backends.qt_compat import QtCore, QtGui
    print (QtCore) # just to make sure this is PyQt

**Comment by gamaanderson** [comment]
@nguy I can get the same error when I force loading PySide with `matplotlib.rcParams['backend.qt4']='PySide'`. it opens the file but fails as soon as it create the Display (canvas).

**Comment by nguy** [comment]
@vanandel You do [this](https://github.com/nguy/lrose-soloPy/blob/master/lrose_solopy/QtVariant.py) in lrose_solopy. Did you see any types of failures before implementing this?

**Comment by vanandel** [comment]
I don’t recall this type of failure.  I was attempting to side-step the
issue of whether the user had PySide or PyQt.

When I add the lines

from matplotlib.backends.qt_compat import QtCore, QtGui
print (QtCore) # just to make sure this is PyQt

The test application works, and prints:

<module 'PySide.QtCore' from
'/usr/local/anaconda/lib/python2.7/site-packages/PySide/QtCore.so’>

Following the advice of

http://matplotlib.org/1.4.0/faq/usage_faq.html#how-do-i-select-pyqt4-or-pyside

$ export QT_API=pyqt

The test application prints

<module 'PyQt4.QtCore' from
'/usr/local/anaconda/lib/python2.7/site-packages/PyQt4/QtCore.so’>

and works.

**Comment by gamaanderson** [comment]
@vanandel So you Matplotlib is loading PySide even with the `matplotlib.rcParams['backend.qt4']='PyQt4'`!? And with the QT_API flag does artview works?

@nguy may be we could QtCore, QtGui from matplotlib? And most important should we do it? I can see some reasons why the may be a bad idea.

**Comment by nguy** [comment]
Wow, this seems strange because I expected the rcParams line to set the behavior for the session.

I wonder if matplotlib is using [this file](https://github.com/epage/PythonUtils/blob/master/util/qt_compat.py) linked from the official Qt page as their qt_compat? I'm not quite sure how it's deployed, but it appears to look for PySide first (unless I'm misreading the script).

@vanandel just to confirm if you start a fresh python session and type:
```
import matplotlib
print(matplotlib.rcParams['backend.qt4'])
```
It comes back with PySide?

**Comment by nguy** [comment]
@gamaanderson I'm not if using the matplotlib method is a good idea either.
One big concern is that if the plotting in PyArt and subsequently ARTview changes to a GPU-based package. Of course this is problematic throughout the code.

We could I guess try to catch and error and use the matplotlib.rcParams or alert user to set QT_API environmental variable. Not the best solutions in mind either...

**Comment by vanandel** [comment]
OK - my bad -   I had export QT_API=pyside in my .bash_profile, so that’s
why matplotlib was using pyside.

If I don’t have QT_API set, or I set QT_API=pyqt, then artview works.

Since artview doesn’t seem to work with pyside, perhaps it could check if
QT_API is set to pyside, print a helpful error message, and then exit?

Would it be hard to use a compatibility layer, as I did in lrose_solopy?

**Comment by gamaanderson** [comment]
Nice, we have figure it out!

testing would be simple, it is just bad having to do every time we start up. We could test it when installing, but as it is bash dependent some cases can still get thought.

using both could be possible, but we still need to be sure of be using the same one as matplotlib, and god knows what matplotlib could do (e.g. PyQt5).

I must think a little, but this should definitely be addressed somehow.

**Comment by nguy** [comment]
@vanandel I just looked throught the lrose code and I don't think that script is actually used. All internal calls use PySide.

The test for QT_API as an environmental variable should be fairly easy using ```os.environ['QT_API']```. Though I'm not sure a useful message wouldn't just annoy the user. I don't think testing when installing is a good idea in case system settings change - at which point a reinstallation would be required.

The best probably solution IMO at this time would be to deploy a test on startup and somehow propagate that choice through the code. Not sure how to do that.
We could also test each time it is needed and build a hook with the class something like [this](http://stackoverflow.com/questions/8052386/how-can-you-easily-select-between-pyqt-or-pyside-at-runtime). But that seems inefficient.

**Comment by vanandel** [comment]
There’s a discussion here:
https://wiki.qt.io/Differences_Between_PySide_and_PyQt

about compatibility layers that let you support both.  They seem to
recommend python_qt_binding.

**Comment by gamaanderson** [comment]
Testing the environmental is fairy simple, but may be vulnerable, a more robust check would be

    from matplotlib.backends.qt_compat import QtCore, QtGui
    isinstance(QtCore, PyQt4.QtCore)

big problem qt_compat is in matplotlib just since may 2014, around version 1.4

given a look in the code there is not clear way to predict or force which one (PyQt4, PyQt4v2, PySide or PyQt5) matplotlib will use.

**Comment by nguy** [comment]
I hesitate to add another dependent library, these can get away pretty quick. 
I'm sure there are people out there using matplotlib <v1.4, so that could cause issues. Having our own qt_compat might be the most effective. But I could see PyQt5 becoming more pronounced in the next couple of years.
I really don't know what the best answer is.

@gamaanderson why is the environmental variable test vulnerable?

**Comment by gamaanderson** [comment]
it is vulnerable because you are testing what matplotlib is supposed to do, not what it have done. If it fails to use that the variable ask it will try something else and not fail.

**Comment by nguy** [comment]
Well you could update the environmental variable before matplotlib opens, BUT we really don't want to change a users settings.

This would just allow the info to be passed to user that PySide will fail if we don't support it.

**Pull request merged**
