### PR TITLE
select region: update points when tilt changes

### PR DESCRIPTION
**Pull request by gamaanderson**
addresses old complain that points from select region get outdate by changing the sweep.

important discovery: function exported using shared variable can be update (i.e. call the `update` method) to reflect a change in the expected function results. This is really good.

Not sure if this is a strong or a weak update though, for now I set it to strong.

### CODE REVIEW

**Comment by nguy** [comment]
What are you using for a weak vs strong update definition?

**Comment by nguy** [comment]
I'm just trying to follow along. Any shared variable should have the ability to be updated/changed the way the code is written? In this case the function that is called returns an updated shared variable, correct?

**Comment by gamaanderson** [comment]
in general weak update indicate components not to perform too intensive calculations or that changes are only superficial, but in the end it is case specific, there is no general rule.

no, the function don't return a shared variable. The shared variable `.value` is a function. For instance `VpathInteriorFunc.value` is equal to `RadarDisplay.getPathInteriorValues`

**Comment by nguy** [comment]
Aha, I see. In this case it is sort of grey whether it's strong or weak.

**Comment by nguy** [comment]
Looks good. I did find another issue we should address at some point, I'll open a ticket.

**Pull request merged**
