### PR TITLE
Topography Map

### PR DESCRIPTION
**Pull request by gamaanderson**
issue #114.

This is not a 100% user friendly function to add a map to display, but rather it shows the option. As we depend on data that we do not have, I would not develop this further unless someone really needs.

### CODE REVIEW

**Comment by gamaanderson** [comment]
adding an image would follow the same principle, we need to figure it out what we really want and a format.

**Comment by nguy** [comment]
Sorry for the delay in getting to this, I'm at a conference in England this week. 

Why did you decide to convert the display into a shared variable? I don't see what we gain from that.

**Comment by nguy** [comment]
I am getting the following error right now. I must have updated something and broke mpl_toolkits.
```
  File "/Users/guy/anaconda/bin/artview", line 4, in <module>
    import artview.__main__
  File "/Users/guy/anaconda/lib/python2.7/site-packages/artview/__init__.py", line 56, in <module>
    from . import plugins
  File "/Users/guy/anaconda/lib/python2.7/site-packages/artview/plugins/__init__.py", line 26, in <module>
    tmp = __import__(module[:-3], locals(), globals())
  File "/Users/guy/anaconda/lib/python2.7/site-packages/artview/plugins/background.py", line 11, in <module>
    from mpl_toolkits.basemap import shiftgrid, cm
  File "/Users/guy/anaconda/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 30, in <module>
    from mpl_toolkits.basemap import pyproj
ImportError: cannot import name pyproj
```

**Comment by nguy** [comment]
Geez, got it. Apparently basemap requires geos <=3.3.3 and it had gotten upgraded to 3.3.5 UGH!

**Comment by nguy** [comment]
Hmm, okay it is working now. It takes so long to load that I'm not sure this method is worth deploying. In addition, in the example data I chose, the grid lower left appeared in the middle of the display window.

I wonder if we should look at other options, such as Cartopy. I haven't played with it enough to know if it is much faster. @jjhelmus @scollis @swnesbitt do you have any idea about speed between basemap and cartopy?
Or do you have any other ideas for topo/boundary map for ARTview?

**Comment by jjhelmus** [comment]
I have not yet had the time to properly investigate Cartopy but it is on my list to packages that I need to give a good test drive.  One difficultly is that it cannot be installed from the `defaults` channel in conda, although `conda-forge` does provide packages for Windows, OS X and Linux.

**Comment by scollis** [comment]
Ditto @jjhelmus At Scipy two weeks ago in the Matplotlib BOFF we found out that Jeff will not be supporting basemap any more. Ben Root will continue for two years but has warned if another option comes up he will move away. Our sticking issue in Py-ART is that it is not in the default channel for Conda although it does have conda-forge packages. (as @jjhelmus pointed out.. should have read his full post before wasting keystrokes.)

**Comment by scollis** [comment]
ps: This is why you need to go to scipy @nguy

**Comment by gamaanderson** [comment]
@nguy the reason I turn display into a shared variable it because I need it in the background component to retrive the basemap instance, that is the only reason and I don't see any good reason against it.

Did you tested in the grid or radar? 

It does take some time, but not that much. You probably opened the topo file from the url, that does take a lot, but if you have the file in your local drive it is faster. There is no good way of downloading, but I can pass you the file tomorow. I have already looked inside the basemap source code, it is really bad, I will be happy to change it in pyart/artview if we have a good alternative, but for now we need to use it.

**Comment by nguy** [comment]
@scollis I know!! I would love to go, but no funding this year for that. Hopefully in the future. I had heard some rumors about basemap and would love to move on from it. I'm concerned about putting in a dependency to package that is very likely to not exist soon.

@jjhelmus If you take for a drive let me know. I'm in the same boat, just trying to find time do that.

**Comment by nguy** [comment]
@gamaanderson I see what you did there. I like the idea, but I think that we should somehow put up some warnings for the user that this process could be potentially slow, especially if the file needs to be retrieved from the URL. 

Here's a thought: would a separate plugin to create a boundaries/topo image to put behind the radar data imagery be a better way to go. I'm thinking the user could generate the image and save to a local directory and then select that for display. I think this is what @CSlocumWX told me he does for his [online radar loop](http://schubert.atmos.colostate.edu/~cslocum/nexrad.php)

**Comment by gamaanderson** [comment]
Do you have any ideia where that warning could be places.

If open an image, how can I geolocalise it?

**Comment by nguy** [comment]
Honestly I'm not sure. I hate to add something like this, but a pop up warning with continue or cancel would work. Delayed loading of the file with a "Go" button or such might also allow a big red warning to put onto the menu.

I'm hoping to get more info on how that has been done with geolocating an image.

**Comment by jjhelmus** [comment]
I gave `cartopy` a test drive over the last two days and from my experience I don't think it is ready for use in Py-ART yet.  The specific issue I kept running into is that the it is unclear what units must be specified in the various projections.  For reference I was trying to re-create the figure from the [Create a PPI plot on a basemap](http://arm-doe.github.io/pyart/dev/auto_examples/plotting/plot_ppi_basemap_with_rings.html) figure from the Py-ART examples.

With `basemap` once a **Basemap** instance is initialized, data can be plotted in coordinates of meters or latitude and longitude by setting the `latlon` argument to the plotting routines.  Additionally, the **Basemap** instance can also be used to convert between Geographic (lon/lat) and Map Projection (x/y) coordinates.   

In `cartopy` each projection seems to have its own internal coordinate system whose units are not specified.  These seems to work fine if you have data that is already in one of these coordinate systems, like in the packages example's, but I could not figure out how to reliably transform radar data into the these coordinate systems.  I was able to get data to appear on maps but it was often incorrectly placed because of this issue.  Also, I did not find the package to be significantly faster than `basemap`

That said, this was my first experience with `cartopy`.  I might have been missing some fundamental understanding of how the package works.  If anyone else has luck getting radar data to plot with `cartopy` I would enjoy hearing about it.

**Comment by gamaanderson** [comment]
I have gone into the source of `cartopy`, and I must say I liked what I see. It is not perfect, but it is basic a simple cython interface that work direct over the c proj4 api. So the map units is the same as proj4, without the modifications basemap does. The documentation is in fact not that great, but the functionalists appear to be there.

Converting to latlon is not as direct, but the `transform_points` allow to transform between any two coordinate system, to get latlon one must only provide a simple instance of `cartopy.crs.Geodetic`. Also what in interesting, although I'm not sure it was a good ideia, `cartopy` actually modifies `matplotlib` (I believe) so the new feature are actually in the `axes` class it self

I will try to see if a get an working example of the map display with cartopy

**Comment by scollis** [comment]
@dopplershift Can you comment on this thread? Specifically @jjhelmus concerns.. We want Py-ART to work with MetPy

**Comment by jjhelmus** [comment]
Would be really interested in if you can get an example work.  I tried using `cartopy.crs.Geodetic` as a longitude, latitude projection but was not able to get anything working.  Here is the script I was trying to get working.

``` Python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import pyart

# read in the radar file
filename = 'nsaxsaprppiC1.a1.20140201.184802.nc'
radar = pyart.io.read(filename, delay_field_loading=True)

# pull put parameters from the radar
lat_radar = float(radar.latitude['data'][0])
lon_radar = float(radar.longitude['data'][0])

field_data = radar.get_field(1, 'reflectivity_horizontal')
sweep_slice = radar.get_slice(1)
gate_lats = radar.gate_latitude['data'][sweep_slice]
gate_lons = radar.gate_latitude['data'][sweep_slice]

# set up projections
plot_proj = ccrs.LambertConformal(
    central_longitude=lon_radar, central_latitude=lat_radar)
geo_proj = ccrs.Geodetic()

# plot the data
ax = plt.axes(projection=plot_proj)

# First attempt, plot the data using pcolormesh
# ValueError: invalid transform: Spherical pcolormesh is not supported -  consider using PlateCarree/RotatedPole.
"""
ax.pcolormesh(
    gate_lons, gate_lats, field_data, vmin=-20, vmax=20, transform=geo_proj)
"""

# Second attempt, transform the gate longitudes and latitudes into a pcolormesh
# supported projection.
# File ".../cartopy/mpl/geoaxes.py", line 1278, in _pcolormesh_patched
#    if t and any(t.contains_branch_seperately(self.transData)):
# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
rotpol_proj = ccrs.RotatedPole(
    pole_longitude=lon_radar, pole_latitude=lat_radar)
rotpol_arr = rotpol_proj = rotpol_proj.transform_points(
    geo_proj, gate_lons.flatten(), gate_lats.flatten())
X = rotpol_arr[:, 0].reshape(gate_lons.shape)
Y = rotpol_arr[:, 1].reshape(gate_lats.shape)
ax.pcolormesh(X, Y, field_data, vmin=-20, vmax=20, transform=rotpol_proj)


min_lon=-157.1
max_lon=-156
min_lat=71.2
max_lat=71.6
x_min, y_min = plot_proj.transform_point(min_lon, min_lat, geo_proj)
x_max, y_max = plot_proj.transform_point(max_lon, max_lat, geo_proj)
ax.set_xlim(x_min, x_max)
ax.set_ylim(y_min, y_max)
ax.coastlines('10m')

plt.show()
```

**Comment by dopplershift** [comment]
So a few comments:

1. Basemap is end-of-life'd, so it would be unwise to add any new dependencies on it (we no longer teach Basemap in our workshops).
2. CartoPy is the only functional alternative that I am aware of, and it has developers at the UK Met office funded to work on it.
3. Fundamentally, CartoPy works by using matplotlib's transform framework. You specify one coordinate system for the Axes (the coordinate system for plotting) and when you plot, you can optionally specify the coordinates for the data. For instance `Geodetic` or `PlateCarree` for lon/lat, or`Mercator` if you've got model output on that grid.
4. Don't expect speed improvements with CartoPy--expect a better API.
5. The big benefit of CartoPy's API is the lack of needing to reproject by hand--just specify the projections at the right time--this includes working automatically for warping/interpolating images between projections

Here's how I've plotted radar data from raw NEXRAD level 3 pulled over OPeNDAP (based on a [notebook](https://nbviewer.jupyter.org/github/Unidata/unidata-python-workshop/blob/master/notebooks/Siphon%20Radar%20Server.ipynb) from our workshop):
```python
import matplotlib.pyplot as plt
import numpy as np
import cartopy
from netCDF4 import Dataset

data = Dataset('http://thredds.ucar.edu/thredds/dodsC/nexrad/level3/N0Q/FTG/20160728/Level3_FTG_N0Q_20160728_2125.nids')
rng = data.variables['gate'][:]
az = data.variables['azimuth'][:]
ref = data.variables['BaseReflectivityDR'][:]

x = rng * np.sin(np.deg2rad(az))[:, None]
y = rng * np.cos(np.deg2rad(az))[:, None]
ref = np.ma.array(ref, mask=np.isnan(ref))

# Create projection centered on the radar. This allows us to use x
# and y relative to the radar.
proj = cartopy.crs.LambertConformal(central_longitude=data.RadarLongitude,
                                    central_latitude=data.RadarLatitude)

# New figure with specified projection
fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(1, 1, 1, projection=proj)

# Grab state borders
state_borders = cartopy.feature.NaturalEarthFeature(
    category='cultural', name='admin_1_states_provinces_lines',
    scale='50m', facecolor='none')
ax.add_feature(state_borders, edgecolor='black', linewidth=2, zorder=2)

# Counties
#counties = cartopy.io.shapereader.Reader('../data/counties.shp')
#ax.add_geometries(counties.geometries(), cartopy.crs.PlateCarree(),
#                  facecolor='None', edgecolor='grey', zorder=1)

# Set limits in lat/lon space
ax.set_extent([-109, -102, 37, 42])

mesh = ax.pcolormesh(x, y, ref, zorder=0)
```

**Comment by dopplershift** [comment]
Granted, I've not really projected the gates, just used them as native to the coordinate system.

**Comment by dopplershift** [comment]
Here's what that looks like:
image

**Comment by scollis** [comment]
So you are reversing the problem? You are projecting lat-lons of shape files to X/Y?


Dr Scott Collis
Purveyor of lofty observations (Atmospheric Scientist) 
Environmental Science Division
Argonne National Laboratory
Mb: +1 630 235 8025
Of: +1 630 252 0550
Become a Py-ART user today! http://arm-doe.github.io/pyart/ <http://arm-doe.github.io/pyart/>

**Comment by dopplershift** [comment]
That's kind of the beauty--I let cartopy handle the projection of the map information. Except where I manually add a shapefile; in that case I have to tell it to use `PlateCarree`.

**Comment by jjhelmus** [comment]
@dopplershift Your example seems to assume that the native units of CartoPy's LambertConformal coordinate reference system are meters, I do not think this is true.  At least when I plot radar data it does not alight with the coastline as it does with Basemap.  Maybe I'm doing something wrong.

``` Python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import pyart

# read in the radar file
filename = 'nsaxsaprppiC1.a1.20140201.184802.nc'
radar = pyart.io.read(filename, delay_field_loading=True)

# pull put parameters from the radar
lat_radar = float(radar.latitude['data'][0])
lon_radar = float(radar.longitude['data'][0])
field_data = radar.get_field(1, 'reflectivity_horizontal')
gate_x, gate_y, gate_z = radar.get_gate_x_y_z(1, edges=True)


# plot the data
proj = ccrs.LambertConformal(
    central_longitude=lon_radar, central_latitude=lat_radar)
fig = plt.figure()
ax = plt.axes(projection=proj)
ax.pcolormesh(
    gate_x, gate_y, field_data, vmin=-20, vmax=20, cmap='pyart_NWSRef')

geo_proj = ccrs.Geodetic()
x_min, y_min = proj.transform_point(-157.1, 71.2, geo_proj)
x_max, y_max = proj.transform_point(-156.0, 71.6, geo_proj)
ax.set_xlim(x_min, x_max)
ax.set_ylim(y_min, y_max)

ax.coastlines('10m')
plt.show()
```
figure_1


Notice that the clutter returns do not line up with the peninsula.  Compare this to the same data, same projection with Basemap from the [Py-ART examples](http://arm-doe.github.io/pyart/dev/auto_examples/plotting/plot_ppi_basemap_with_rings.html)
plot_ppi_basemap_with_rings_1

**Comment by gamaanderson** [comment]
@jjhelmus I can't see anything wrong, but I don't think the problem are the units, the error is to small for that, also notice that the origin is displaced. Maybe the coastlines are wrong, you could add the latlon grid so that we can compare it. For that 

    ax.gridlines(xlocs=[-157, -156.8,  lon_radar, -156.6, -156.4, -156.2],
                 ylocs=[71.2, 71.3, lat_radar, 71.4, 71.5, 71.6])

**Comment by tjlang** [comment]
As a general political comment, I find it interesting that the main map-plotting-projection module for Python is being put to pasture without a real alternative in place. Kind of a stunning lack of foresight there. That's a major gap that needs to be filled, and quickly. Are there funding opportunities to get more folks developing on Cartopy?

**Comment by scollis** [comment]
It’s a valid one

Basemap is Jeff Whittaker .. Same guy behind NerCDF4-python .. He gave a talk at the Python symposium a few years ago and made clear he maintains basemap for his use only.. his time was stretched too thin.

As for why Cartopy verses Basemap?

For one Cartopy has MetOffice support (how much is uncertain) two, and I will defer to @jjhelmus and @dopplershift on this, but I do believe the Basemap API was a bit cumbersome.. We all know it is slow..

But your comment is very valid..

Perhaps we should seek out Ben Root @WeatherGod (now there is a title) and ask

Dr Scott Collis
Purveyor of lofty observations (Atmospheric Scientist) 
Environmental Science Division
Argonne National Laboratory
Mb: +1 630 235 8025
Of: +1 630 252 0550
Become a Py-ART user today! http://arm-doe.github.io/pyart/ <http://arm-doe.github.io/pyart/>

**Comment by WeatherGod** [comment]
Basemap is no longer maintained by Jeff Whittaker; I am now the maintainer. As I announced at a couple of BoFs during SciPy 2016, I will make sure Basemap keeps working up until 2020. I am just about ready to put out a new release once I figure out a few niggling details about the new vector datasets that it needs.

As I specified in the BoFs, Cartopy is not feature-parity with Basemap, yet, however it has a much more solid foundational design than Cartopy. Therefore, I encouraged the attendees to begin developing new software against Cartopy, and to look into porting old software over. Any missing features in Cartopy found in that process should be reported as a bug to Cartopy.

Basemap's codebase is too much of a beast to refactor and it requires 2to3 in order to be usable on py3k, which is why I choose 2020 as a target date for EoL. I have no plans for adding new features to Basemap, especially since my reasons for taking over Basemap has been to support scripts that are in use at my job. That said, I would not refuse PRs that provide new features, and I certainly would not refuse any efforts to fix up the codebase.

I hope this answers questions about the "lack of foresight". I have given this a lot of thought, and my thinking is that ambiguity about Basemap's future only hurts Cartopy's future. Making a clear statement about Basemap's EoL and putting it out far enough should help drive the necessary resources to Cartopy to get it to mature while causing the least amount of pain to the community at large.

**Comment by scollis** [comment]
Perfect @WeatherGod , thankyou. I am sure @tjlang did not mean it to offend and was just unaware of what was going on behind the scenes. 

It seems to be very prudent for the many of us who rely on good projection aware software to be looking now to Cartopy, seeing what it can and can not do for our needs and working with the Cartopy developers (perhaps even contributing) to build the package up. 

It seems to me a Cartopy sprint at Scipy or other venues (Python symposium in Seattle?) may be a very good idea..

**Comment by tjlang** [comment]
Thanks for this response, @WeatherGod. This is very helpful to know. Sorry, I should have been more specific. This is about more than one person, and my comments are directed at the community itself. Geographic plotting and transformation is pretty critical to Earth science. It is troubling to learn that the main Python package for this has a single point of failure. This is something that we as a community should address. No one person should carry the load for something so crucial. The fact that you are willing to support basemap to 2020 is amazingly helpful and generous, and you have our gratitude. I hope, as you do, that the looming deadline stirs the community to action. @scollis presents some good ideas to start us out, but this is an issue that more institutions should be supporting, in addition to UKMO. I'll see what I can do to get folks at NASA more involved.

**Comment by jjhelmus** [comment]
Coming back to plotting radar data with CartoPy vs Basemap, I worked to par down my example some and added a latlon grid.  The data still seems to me to be scaled incorrectly.
Using CartoPy:
``` Python
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import pyart

# read in the radar file
filename = 'nsaxsaprppiC1.a1.20140201.184802.nc'
radar = pyart.io.read(filename, delay_field_loading=True)

# pull put parameters from the radar
lat_radar = float(radar.latitude['data'][0])
lon_radar = float(radar.longitude['data'][0])
field_data = radar.get_field(1, 'reflectivity_horizontal')
field_data = np.ma.masked_less(field_data, 10)
gate_x, gate_y, gate_z = radar.get_gate_x_y_z(1, edges=True)

# plot the data
proj = ccrs.LambertConformal(
    central_longitude=lon_radar, central_latitude=lat_radar)
fig = plt.figure(figsize=(10, 10))
ax = plt.axes(projection=proj)
x0 = 0
y0 = 0
ax.pcolormesh(gate_x + x0, gate_y + y0, field_data, vmin=0, vmax=40)

ax.coastlines('10m')
ax.set_extent([-157.1, -156.0, 71.2, 71.4])
ax.gridlines(
    xlocs=[-156.7, -156.3],
    ylocs=[71.3, 71.24])
plt.show()
```
cartopy


Using basemap
``` Python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap
import pyart

# read in the radar file
filename = 'nsaxsaprppiC1.a1.20140201.184802.nc'
radar = pyart.io.read(filename, delay_field_loading=True)

# pull put parameters from the radar
lat_radar = float(radar.latitude['data'][0])
lon_radar = float(radar.longitude['data'][0])
field_data = radar.get_field(1, 'reflectivity_horizontal')
field_data = np.ma.masked_less(field_data, 10)
gate_x, gate_y, gate_z = radar.get_gate_x_y_z(1, edges=True)

# plot the data
fig = plt.figure(figsize=(10, 10))
basemap = Basemap(
    llcrnrlon=-157.1, urcrnrlon=-156.0,
    llcrnrlat=71.2, urcrnrlat=71.4,
    lat_0=lat_radar, lon_0=lon_radar,
    projection='lcc', resolution='h')
x0, y0 = basemap(lon_radar, lat_radar)
basemap.pcolormesh(gate_x + x0, gate_y + y0, field_data, vmin=0, vmax=40)

basemap.drawcoastlines(linewidth=1.25)
basemap.drawmeridians([-156.7, -156.3])
basemap.drawparallels([71.3, 71.24])
plt.show()
```

basemap

The [nsaxsaprppiC1.a1.20140201.184802.nc](https://engineering.arm.gov/~jhelmus/pyart_example_data/) file is available for download if anyone wants to play around with this.

**Comment by gamaanderson** [comment]
so I got the problem with the scaling. [cartopy](http://scitools.org.uk/cartopy/docs/latest/crs/projections.html#lambertconformal) set the standard parallels of lcc to (33, 45), to get a 1.0 scaling at origin we need to set it:

    proj = ccrs.LambertConformal(
        central_longitude=lon_radar, central_latitude=lat_radar,
        standard_parallels=(lat_radar,))

I would report that as a bug, and suggest using `central_latitutude` as `standart_parallels` instead of the arbitrary (33, 45).

The result is the following
figure_1

the coastlines are still off, but the data match the grid.

**Comment by gamaanderson** [comment]
I should also say that the coastlines are off also when using AzimuthalEquidistant, so the issue is independent of projection.

**Comment by WeatherGod** [comment]
Yeah, it looks like something is possibly wrong with the underlying
coastline data that Cartopy uses. I find it kind of funny that radar ground
clutter is being used to detect bugs in a display package...

**Comment by gamaanderson** [comment]
FYI, I'm using v 0.13.1, since I don't have the dep's for version 0.14

**Comment by jjhelmus** [comment]
Good find on the `standard parallels` parameter @gamaanderson, thats seems to fix things.  

From what I can tell the coastline difference between basemap and cartopy's `coastlines` method stems from the difference source from which the coastline data is derived.  Basemap uses data from GSHHS where as cartopy uses Natural Earth.  Luckily cartopy can plot data from both which shows the difference quite clearly:

``` Python
import cartopy
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

# projection
lat_0 = 71.2
lon_0 = -156.5
proj = ccrs.LambertConformal(central_longitude=lon_0, central_latitude=lat_0,
                             standard_parallels=(lat_0, ))

# set up the axes
fig = plt.figure(figsize=(10, 10))
ax = plt.axes(projection=proj)

# add coastlines from Natural Earth
ax.coastlines('10m')

# add coastlines from GSHHS
shpfile = cartopy.io.shapereader.gshhs('h')
shp = cartopy.io.shapereader.Reader(shpfile)
ax.add_geometries(
    shp.geometries(), ccrs.PlateCarree(), edgecolor='red', facecolor='none')

ax.set_extent([-157.0, -156.0, 71.1, 71.5])
plt.show()
```

barrow

**Comment by jjhelmus** [comment]
...and the cartopy plot now matches Basemap

``` Python
import numpy as np
import matplotlib.pyplot as plt
import cartopy
import cartopy.crs as ccrs
import pyart

# read in the radar file
filename = 'nsaxsaprppiC1.a1.20140201.184802.nc'
radar = pyart.io.read(filename, delay_field_loading=True)

# pull put parameters from the radar
lat_radar = float(radar.latitude['data'][0])
lon_radar = float(radar.longitude['data'][0])
field_data = radar.get_field(1, 'reflectivity_horizontal')
field_data = np.ma.masked_less(field_data, 10)
gate_x, gate_y, gate_z = radar.get_gate_x_y_z(1, edges=True)

# plot the data
proj = ccrs.LambertConformal(
    central_longitude=lon_radar, central_latitude=lat_radar,
    standard_parallels=(lat_radar, ))
fig = plt.figure(figsize=(10, 10))
ax = plt.axes(projection=proj)
ax.pcolormesh(gate_x, gate_y, field_data, vmin=0, vmax=40)

shpfile = cartopy.io.shapereader.gshhs('h')
shp = cartopy.io.shapereader.Reader(shpfile)
ax.add_geometries(
    shp.geometries(), ccrs.PlateCarree(), edgecolor='black', facecolor='none')
ax.set_extent([-157.1, -156.0, 71.2, 71.4])

ax.gridlines(
    xlocs=[-156.7, -156.3],
    ylocs=[71.3, 71.24])
plt.show()
```

cartopy_gshhs

Thanks all for the help and sorry to distract from the original discussion on this PR.

**Pull request merged**
